<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/fontello-embedded.css')
                        ->prependStylesheet($this->basePath() . '/css/fontello-embedded.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
    	<div>
			<p><img src="<?php echo $this->basePath('img/Lune_de_Pontlieue_NB.jpg') ?>" width="100%"/></p>
		</div>
        <nav class="navbar navbar-inverse " role="navigation">
            <div class="container">
                <!--<div class="navbar">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>-->
                <div class="collapse navbar-collapse">
                    <div class="">
                        <ul class="nav nav-justified col-md-offset-1">
                            <li>
                                <ul class="nav navbar-nav navbar-left">
                                    <li class=""><img class="img-circle" ><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                                    <li class=""><a href="<?php echo $this->url('bio') ?>"><?php echo $this->translate('Bio') ?></a></li>
                                    <li class=""><a href="<?php echo $this->url('tracks') ?>"><?php echo $this->translate('Tracks') ?></a></li>
                                    <li class=""><a href="<?php echo $this->url('contact') ?>"><?php echo $this->translate('Contact') ?></a></li>
                                </ul>
                            </li>
                            <li></li>
                            <li>
                                <ul class="nav navbar-nav navbar-left">
                                    <li class=""><a href="<?php echo $this->url('contact') ?>"><?php echo '<span class="icon icon-facebook"></span>' ?></a></li>
                                    <li class=""><a href="<?php echo $this->url('contact') ?>"><?php echo '<span class="icon icon-twitter"></span>' ?></a></li>
                                    <li class=""><a href="<?php echo $this->url('contact') ?>"><?php echo '<span class="icon icon-pinterest"></span>' ?></a></li>
                                    <li class=""><a href="<?php echo $this->url('contact') ?>"><?php echo '<span class="icon icon-youtube"></span>' ?></a></li>
                                    <li class=""><a href="<?php echo $this->url('contact') ?>"><?php echo '<span class="icon icon-instagramm"></span>' ?></a></li>
                                    <li class=""><a href="<?php echo $this->url('contact') ?>"><?php echo '<span class="icon icon-mail-squared"></span>' ?></a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div><!--/.nav-collapse -->

            </div>
        </nav>
        <div class="container">

            <div class="row">
                <div class="col-xs-6 col-md-3">
                    <a href="#" class="thumbnail">
                        <img data-src="<?php echo $this->basePath('img/vignette-sang.jpg') ?>">
                    </a>
                </div>
                ...
            </div>

            <ul class="nav nav-justified">
                <li><img class="img-circle" src="<?php echo $this->basePath('img/vignette-sang.jpg') ?>" width="10%"></li>
                <li><img class="img-circle" src="<?php echo $this->basePath('img/vignette-sang.jpg') ?>" width="10%"></li>
                <li><img class="img-circle" src="<?php echo $this->basePath('img/vignette-sang.jpg') ?>" width="10%"></li>
            </ul>


            <?php echo $this->content; ?>
            <hr>
            <footer>
                
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
